In [2]:
import torch 
from samplers import SignalSamplerQAM

data_sampler = SignalSamplerQAM(n_dims=2, M=16)

b_size = 10
n_points = 5

n_states = data_sampler.sig_set_size

sig, sig_ids = data_sampler.sample_xs(b_size=b_size, n_points=n_points)
sig_ids_one_hot = torch.eye(n_states)[sig_ids]

print('sig = ', sig)
print('sig ids = ', sig_ids)
print('sig ids one hot = ', sig_ids_one_hot)


sig =  tensor([[[ 0.9487,  0.9487],
         [ 0.9487,  0.9487],
         [-0.3162,  0.9487],
         [ 0.3162, -0.9487],
         [ 0.3162,  0.3162]],

        [[-0.9487, -0.3162],
         [ 0.3162, -0.3162],
         [ 0.9487, -0.9487],
         [ 0.3162,  0.9487],
         [ 0.3162, -0.9487]],

        [[ 0.3162,  0.3162],
         [-0.3162,  0.9487],
         [ 0.3162,  0.3162],
         [-0.9487,  0.3162],
         [-0.9487, -0.9487]],

        [[-0.9487, -0.3162],
         [ 0.9487, -0.3162],
         [ 0.3162, -0.9487],
         [-0.9487,  0.3162],
         [ 0.3162, -0.3162]],

        [[ 0.3162,  0.3162],
         [ 0.3162, -0.9487],
         [-0.9487,  0.9487],
         [ 0.9487, -0.3162],
         [ 0.9487,  0.3162]],

        [[ 0.3162,  0.9487],
         [-0.9487,  0.3162],
         [-0.9487,  0.3162],
         [-0.9487, -0.9487],
         [ 0.3162,  0.9487]],

        [[ 0.3162, -0.3162],
         [-0.3162,  0.3162],
         [-0.9487, -0.9487],
         [ 0.3162, -0.94

In [1]:
import numpy as np


A = np.random.randint(10, size=(2,4,3))

B = A.reshape(-1, 3)

C = B.reshape(2,4,3)

print('A = ', A)
print('B = ', B)
print('C = ', C)

A =  [[[3 8 6]
  [7 1 4]
  [7 8 0]
  [2 5 3]]

 [[8 2 0]
  [4 0 7]
  [8 4 8]
  [8 2 7]]]
B =  [[3 8 6]
 [7 1 4]
 [7 8 0]
 [2 5 3]
 [8 2 0]
 [4 0 7]
 [8 4 8]
 [8 2 7]]
C =  [[[3 8 6]
  [7 1 4]
  [7 8 0]
  [2 5 3]]

 [[8 2 0]
  [4 0 7]
  [8 4 8]
  [8 2 7]]]
